=== UniTrader/UTXReImagined/maps/XU_ep1_universe/map.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:element name="macros">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" ref="macro"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="macro">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="0" ref="component"/>
                <xs:element minOccurs="0" ref="connections"/>
                <xs:element minOccurs="0" ref="properties"/>
            </xs:sequence>
            <xs:attribute name="class" type="xs:NCName"/>
            <xs:attribute name="connection" type="xs:NCName"/>
            <xs:attribute name="name" type="xs:NCName"/>
            <xs:attribute name="path"/>
            <xs:attribute name="ref" type="xs:NCName"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="component">
        <xs:complexType>
            <xs:attribute name="connection" type="xs:NCName"/>
            <xs:attribute name="ref" use="required" type="xs:NCName"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="connections">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="0" maxOccurs="unbounded" ref="connection"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="connection">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="0" ref="offset"/>
                <xs:element minOccurs="0" maxOccurs="unbounded" ref="macro"/>
            </xs:sequence>
            <xs:attribute name="name" type="xs:NCName"/>
            <xs:attribute name="path"/>
            <xs:attribute name="ref" use="required" type="xs:NCName"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="offset">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="0" ref="position"/>
                <xs:element minOccurs="0" ref="quaternion"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="position">
        <xs:complexType>
            <xs:attribute name="x" use="required" type="xs:double"/>
            <xs:attribute name="y" use="required" type="xs:decimal"/>
            <xs:attribute name="z" use="required" type="xs:double"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="quaternion">
        <xs:complexType>
            <xs:attribute name="qw" use="required" type="xs:double"/>
            <xs:attribute name="qx" use="required" type="xs:double"/>
            <xs:attribute name="qy" use="required" type="xs:double"/>
            <xs:attribute name="qz" use="required" type="xs:double"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="properties">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="0" ref="boundaries"/>
                <xs:element minOccurs="0" ref="controls"/>
                <xs:element minOccurs="0" ref="identification"/>
                <xs:choice minOccurs="0">
                    <xs:element ref="build"/>
                    <xs:element ref="configuration"/>
                </xs:choice>
                <xs:element minOccurs="0" ref="sounds"/>
                <xs:element minOccurs="0" ref="area"/>
                <xs:element minOccurs="0" ref="icon"/>
                <xs:choice minOccurs="0">
                    <xs:element ref="map"/>
                    <xs:element ref="region"/>
                </xs:choice>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="boundaries">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="0" ref="boundary"/>
            </xs:sequence>
            <xs:attribute name="priority" type="xs:integer"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="boundary">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" ref="splineposition"/>
                <xs:element ref="size"/>
            </xs:sequence>
            <xs:attribute name="class" use="required" type="xs:NCName"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="splineposition">
        <xs:complexType>
            <xs:attribute name="inlength" use="required" type="xs:decimal"/>
            <xs:attribute name="outlength" use="required" type="xs:decimal"/>
            <xs:attribute name="tx" use="required" type="xs:double"/>
            <xs:attribute name="ty" use="required" type="xs:double"/>
            <xs:attribute name="tz" use="required" type="xs:decimal"/>
            <xs:attribute name="weight" use="required" type="xs:integer"/>
            <xs:attribute name="x" use="required" type="xs:decimal"/>
            <xs:attribute name="y" use="required" type="xs:decimal"/>
            <xs:attribute name="z" use="required" type="xs:decimal"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="size">
        <xs:complexType>
            <xs:attribute name="r" use="required" type="xs:integer"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="controls">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="linear"/>
                <xs:element ref="angular"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="linear">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="time"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="time">
        <xs:complexType/>
    </xs:element>
    <xs:element name="angular">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="roll"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="roll">
        <xs:complexType/>
    </xs:element>
    <xs:element name="identification">
        <xs:complexType>
            <xs:attribute name="description"/>
            <xs:attribute name="name"/>
            <xs:attribute name="owner" type="xs:NCName"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="build">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="0" ref="upgrade"/>
                <xs:element maxOccurs="unbounded" ref="plan"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="plan">
        <xs:complexType>
            <xs:attribute name="sequence" use="required" type="xs:NCName"/>
            <xs:attribute name="stage" use="required" type="xs:integer"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="configuration">
        <xs:complexType>
            <xs:attribute name="ref" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="sounds">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="music"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="music">
        <xs:complexType>
            <xs:attribute name="ref" use="required" type="xs:NCName"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="area">
        <xs:complexType>
            <xs:attribute name="sunlight" type="xs:decimal"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="icon">
        <xs:complexType>
            <xs:attribute name="map" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="map">
        <xs:complexType>
            <xs:attribute name="background" type="xs:NCName"/>
            <xs:attribute name="index" use="required" type="xs:integer"/>
            <xs:attribute name="shortvariation"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="region">
        <xs:complexType>
            <xs:attribute name="ref" use="required" type="xs:NMTOKEN"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="upgrade">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="0" ref="upgrade"/>
            </xs:sequence>
            <xs:attribute name="level" type="xs:decimal"/>
            <xs:attribute name="upgrade" type="xs:NCName"/>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== UniTrader/UTXReImagined/maps/XU_ep1_universe/xri_map_sectors.xml
<?xml version="1.0" encoding="UTF-8"?>
<macros xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="map.xsd">

<!-- ALBION -->
  <macro name="XRI_MAP_SEC_AL_BR_macro" class="sector">
    <component ref="standardsector"/>
    <connections>
      <connection name="XRI_MAP_ZON_AL_BR_Zone01_connection" ref="zones">
        <offset>
          <position x="-80000" y="35000" z="80000"/>
        </offset>
        <macro ref="XRI_MAP_ZON_AL_BR_Zone01_macro" connection="sector"/>
      </connection>
      <connection name="XRI_MAP_ZON_AL_BR_Zone02_connection" ref="zones">
        <offset>
          <position x="0" y="20000" z="175000"/>
        </offset>
        <macro ref="XRI_MAP_ZON_AL_BR_Zone02_macro" connection="sector"/>
      </connection>
      <connection name="XRI_MAP_ZON_AL_BR_Zone03_connection" ref="zones">
        <offset>
          <position x="150000" y="-10000" z="-20000"/>
        </offset>
        <macro ref="XRI_MAP_ZON_AL_BR_Zone03_macro" connection="sector"/>
      </connection>
      <connection name="XRI_MAP_ZON_AL_BR_Zone04_connection" ref="zones">
        <offset>
          <position x="-25000" y="30000" z="-175000"/>
        </offset>
        <macro ref="XRI_MAP_ZON_AL_BR_Zone04_macro" connection="sector"/>
      </connection>
      <connection name="XRI_MAP_ZON_AL_BR_Zone05_connection" ref="zones">
        <offset>
          <position x="50000" y="50000" z="10000"/>
          <quaternion qx="-0.3826834323650898" qy="0" qz="0" qw="0.9238795325112867" />
        </offset>
        <macro ref="XRI_MAP_ZON_AL_BR_Zone05_macro" connection="sector"/>
      </connection>
      <connection name="XRI_MAP_ZON_AL_BR_Zone06_connection" ref="zones">
        <offset>
          <position x="50000" y="-50000" z="-10000"/>
          <quaternion qx="-0.3535533905932738" qy="0.3535533905932738" qz="0.14644660940672624" qw="0.8535533905932737" />
        </offset>
        <macro ref="XRI_MAP_ZON_AL_BR_Zone06_macro" connection="sector"/>
      </connection>
      <connection name="XRI_MAP_ZON_AL_BR_Zone07_connection" ref="zones">
        <offset>
          <position x="-100000" y="-40000" z="-40000"/>
        </offset>
        <macro ref="XRI_MAP_ZON_AL_BR_Zone07_macro" connection="sector"/>
      </connection>
      <connection name="XRI_MAP_ZON_AL_BR_Zone08_connection" ref="zones">
        <offset>
          <position x="-50000" y="-150000" z="-100000"/>
          <!--quaternion qx="-0.70710678118" qy="0" qz="0" qw="0.70710678118" /-->
        </offset>
        <macro ref="XRI_MAP_ZON_AL_BR_Zone08_macro" connection="sector"/>
      </connection>
      <connection name="XRI_MAP_ZON_AL_BR_Zone09_connection" ref="zones">
        <offset>
          <position x="100000" y="80000" z="130000"/>
        </offset>
        <macro ref="XRI_MAP_ZON_AL_BR_Zone09_macro" connection="sector"/>
      </connection>
      
      <connection name="XRI_MAP_ZON_SHW_IW-BR_GateZone_Exit_connection" ref="zones">
        <offset>
          <position x="152000" y="-9000" z="-10000"/>
        </offset>
        <macro ref="XRI_MAP_ZON_SHW_GateZone_Exit_macro" connection="sector"/>
      </connection>

      <connection name="XRI_MAP_ZON_SHW_BR-AS_GateZone_Entry_connection" ref="zones">
        <offset>
          <position x="152000" y="-9000" z="-27000"/>
        </offset>
        <macro ref="XRI_MAP_ZON_SHW_GateZone_Entry_macro" connection="sector"/>
      </connection>

      <connection name="XRI_MAP_ZON_SHW_BR-LA_GateZone_Entry_connection" ref="zones">
        <offset>
          <position x="-10000" y="20000" z="180000"/>
        </offset>
        <macro ref="XRI_MAP_ZON_SHW_GateZone_Entry_macro" connection="sector"/>
      </connection>

      <connection name="XRI_MAP_ZHW_AL_BR_01_connection" ref="zonehighways">
        <offset>
          <position x="0" y="0" z="0"/>
        </offset>
        <macro ref="XRI_MAP_ZHW_AL_BR_01_macro" connection="sector">
          <connections>
            <connection ref="exitpoint">
              <macro path="../../XRI_MAP_ZON_AL_BR_Zone03_connection" connection="Highway01Connection02_gate"/>
            </connection>
            <connection ref="entrypoint">
              <macro path="../../XRI_MAP_ZON_AL_BR_Zone03_connection" connection="Highway01Connection01_gate"/>
            </connection>
          </connections>
        </macro>
      </connection>

      <connection name="XRI_MAP_ZHW_AL_BR_02_connection" ref="zonehighways">
        <offset>
          <position x="0" y="0" z="0"/>
        </offset>
        <macro ref="XRI_MAP_ZHW_AL_BR_02_macro" connection="sector">
          <connections>
            <connection ref="exitpoint">
              <macro path="../../XRI_MAP_ZON_AL_BR_Zone03_connection" connection="Highway02Connection02_gate"/>
            </connection>
            <connection ref="entrypoint">
              <macro path="../../XRI_MAP_ZON_AL_BR_Zone03_connection" connection="Highway02Connection01_gate"/>
            </connection>
          </connections>
        </macro>
      </connection>

      <connection name="XRI_MAP_ZHW_AL_BR_03_connection" ref="zonehighways">
        <offset>
          <position x="0" y="0" z="0"/>
        </offset>
        <macro ref="XRI_MAP_ZHW_AL_BR_03_macro" connection="sector">
          <connections>
            <connection ref="exitpoint">
              <macro path="../../XRI_MAP_ZON_AL_BR_Zone08_connection" connection="Highway03Connection02_gate"/>
            </connection>
            <connection ref="entrypoint">
              <macro path="../../XRI_MAP_ZON_AL_BR_Zone08_connection" connection="Highway03Connection01_gate"/>
            </connection>
          </connections>
        </macro>
      </connection>

      <!-- EXPERIMENTAL: Circular Tubes - used as reference -->
      <!--connection name="XRI_MAP_ZHW_UnitCircle_cclockwise_connection" ref="zonehighways">
        <offset>
          <position x="150000" y="0" z="0"/>
        </offset>
        <macro ref="XRI_MAP_ZHW_UnitCircle_cclockwise_macro" connection="sector">
          <connections>
            <connection ref="exitpoint">
              <macro path="../../XRI_MAP_ZON_AL_BR_Zone03_connection" connection="Highway01Connection02_gate"/>
            </connection>
            <connection ref="entrypoint">
              <macro path="../../XRI_MAP_ZON_AL_BR_Zone03_connection" connection="Highway01Connection01_gate"/>
            </connection>
          </connections>
        </macro>
      </connection>
      <connection name="XRI_MAP_ZHW_UnitCircle_clockwise_connection" ref="zonehighways">
        <offset>
          <position x="150000" y="1000" z="0"/>
        </offset>
        <macro ref="XRI_MAP_ZHW_UnitCircle_clockwise_macro" connection="sector">
          <connections>
            <connection ref="exitpoint">
              <macro path="../../XRI_MAP_ZON_AL_BR_Zone03_connection" connection="Highway01Connection02_gate"/>
            </connection>
            <connection ref="entrypoint">
              <macro path="../../XRI_MAP_ZON_AL_BR_Zone03_connection" connection="Highway01Connection01_gate"/>
            </connection>
          </connections>
        </macro>
      </connection-->

    </connections>
    <properties>
      <identification name="{5554203,1011}" description="{5554203,1012}" />
      <!--sounds>
        <music ref="music_sector_17" />
      </sounds-->
      <area sunlight="0.5"/>
      <map background="part_bg_sec_12" index="1" shortvariation="{5554203,1014}"/>
    </properties>
  </macro>
  
</macros>
